[project]
name = "cs2100"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "coverage>=7.8.2",
    "matplotlib>=3.10.8",
    "mypy>=1.16.0",
    "pandas>=3.0.0",
    "pandas-stubs>=2.3.3.260113",
    "pylint>=3.1.0",
    "pylint-json2checkstyle>=0.0.13",
    "ruff>=0.14.10",
    "ty>=0.0.10",
    "unittest-xml-reporting==3.2.0",
]

[tool.uv.workspace]
members = [
    "homeworks/sp26-hw1-hiteacheryouare",
    "homeworks/sp26-lab0-hiteacheryouare",
]
